import type { LucideIcon } from 'lucide-react';
import {
  Play,
  Clock,
  Zap,
  GitBranch,
  Timer,
  Repeat,
  Variable,
  GitMerge,
  ListPlus,
  ListChecks,
  Trash2,
  FolderPlus,
  FolderCog,
  FolderMinus,
  Receipt,
  ReceiptText,
  Ban,
  MessageCircle,
  Hash,
  BellRing,
} from 'lucide-react';
import type { WorkflowNodeType } from '@/lib/types';

export type NodeCategory = 'trigger' | 'logic' | 'action';

export interface NodeStyleMeta {
  icon: LucideIcon;
  label: string;
  category: NodeCategory;
  bg: string;
  text: string;
  border: string;
  destructive?: boolean;
  description: string;
  defaultConfig: Record<string, unknown>;
}

export const NODE_STYLES: Record<WorkflowNodeType, NodeStyleMeta> = {
  'trigger.manual': {
    icon: Play,
    label: 'Manual Trigger',
    category: 'trigger',
    bg: 'bg-pine-500/10',
    text: 'text-pine-700',
    border: 'border-pine-400/40',
    description: 'Runs only when you click "Run now".',
    defaultConfig: {},
  },
  'trigger.cron': {
    icon: Clock,
    label: 'Schedule',
    category: 'trigger',
    bg: 'bg-pine-500/10',
    text: 'text-pine-700',
    border: 'border-pine-400/40',
    description: 'Runs automatically on a recurring schedule.',
    defaultConfig: { cronExpression: '0 9 * * *' },
  },
  'trigger.event': {
    icon: Zap,
    label: 'Workspace Event',
    category: 'trigger',
    bg: 'bg-pine-500/10',
    text: 'text-pine-700',
    border: 'border-pine-400/40',
    description: 'Runs when something happens in your workspace.',
    defaultConfig: { entityType: 'task', eventName: 'task.created' },
  },

  'logic.if': {
    icon: GitBranch,
    label: 'Condition',
    category: 'logic',
    bg: 'bg-steel-500/10',
    text: 'text-steel-600',
    border: 'border-steel-400/40',
    description: 'Branch the flow based on a condition.',
    defaultConfig: { condition: { left: '', op: 'eq', right: '' } },
  },
  'logic.delay': {
    icon: Timer,
    label: 'Wait',
    category: 'logic',
    bg: 'bg-steel-500/10',
    text: 'text-steel-600',
    border: 'border-steel-400/40',
    description: 'Pause before continuing (up to 1 hour).',
    defaultConfig: { seconds: 60 },
  },
  'logic.forEach': {
    icon: Repeat,
    label: 'For Each',
    category: 'logic',
    bg: 'bg-steel-500/10',
    text: 'text-steel-600',
    border: 'border-steel-400/40',
    description: 'Repeat a linear chain of steps once per item in a list.',
    defaultConfig: { listExpression: '', maxIterations: 50 },
  },
  'logic.setVariable': {
    icon: Variable,
    label: 'Set Variable',
    category: 'logic',
    bg: 'bg-steel-500/10',
    text: 'text-steel-600',
    border: 'border-steel-400/40',
    description: 'Compute and store values for later steps.',
    defaultConfig: { assignments: [{ key: '', valueExpression: '' }] },
  },
  'logic.merge': {
    icon: GitMerge,
    label: 'Merge',
    category: 'logic',
    bg: 'bg-steel-500/10',
    text: 'text-steel-600',
    border: 'border-steel-400/40',
    description: 'Waits for every incoming branch to finish.',
    defaultConfig: {},
  },

  'action.createTask': {
    icon: ListPlus,
    label: 'Create Task',
    category: 'action',
    bg: 'bg-brass-500/10',
    text: 'text-brass-700',
    border: 'border-brass-400/40',
    description: 'Create a new task.',
    defaultConfig: { title: '' },
  },
  'action.updateTask': {
    icon: ListChecks,
    label: 'Update Task',
    category: 'action',
    bg: 'bg-brass-500/10',
    text: 'text-brass-700',
    border: 'border-brass-400/40',
    description: 'Update an existing task.',
    defaultConfig: { taskId: '' },
  },
  'action.deleteTask': {
    icon: Trash2,
    label: 'Delete Task',
    category: 'action',
    bg: 'bg-terracotta-500/10',
    text: 'text-terracotta-600',
    border: 'border-terracotta-400/40',
    destructive: true,
    description: 'Permanently deletes a task. Cannot be undone.',
    defaultConfig: { taskId: '' },
  },
  'action.createProject': {
    icon: FolderPlus,
    label: 'Create Project',
    category: 'action',
    bg: 'bg-brass-500/10',
    text: 'text-brass-700',
    border: 'border-brass-400/40',
    description: 'Create a new project.',
    defaultConfig: { name: '' },
  },
  'action.updateProject': {
    icon: FolderCog,
    label: 'Update Project',
    category: 'action',
    bg: 'bg-brass-500/10',
    text: 'text-brass-700',
    border: 'border-brass-400/40',
    description: 'Update an existing project.',
    defaultConfig: { projectId: '' },
  },
  'action.deleteProject': {
    icon: FolderMinus,
    label: 'Delete Project',
    category: 'action',
    bg: 'bg-terracotta-500/10',
    text: 'text-terracotta-600',
    border: 'border-terracotta-400/40',
    destructive: true,
    description: 'Permanently deletes a project. Cannot be undone.',
    defaultConfig: { projectId: '' },
  },
  'action.createInvoice': {
    icon: Receipt,
    label: 'Create Invoice',
    category: 'action',
    bg: 'bg-brass-500/10',
    text: 'text-brass-700',
    border: 'border-brass-400/40',
    description: 'Create and calculate a new invoice.',
    defaultConfig: { issueDate: '', items: [{ description: '', quantity: 1, unitPrice: 0 }] },
  },
  'action.updateInvoiceStatus': {
    icon: ReceiptText,
    label: 'Update Invoice Status',
    category: 'action',
    bg: 'bg-brass-500/10',
    text: 'text-brass-700',
    border: 'border-brass-400/40',
    description: "Change an invoice's status.",
    defaultConfig: { invoiceId: '', status: 'sent' },
  },
  'action.deleteInvoice': {
    icon: Ban,
    label: 'Delete Invoice',
    category: 'action',
    bg: 'bg-terracotta-500/10',
    text: 'text-terracotta-600',
    border: 'border-terracotta-400/40',
    destructive: true,
    description: 'Permanently deletes an invoice. Cannot be undone.',
    defaultConfig: { invoiceId: '' },
  },
  'action.sendClientMessage': {
    icon: MessageCircle,
    label: 'Message Client',
    category: 'action',
    bg: 'bg-moss-500/10',
    text: 'text-moss-600',
    border: 'border-moss-400/40',
    description: 'Send a message to a client conversation.',
    defaultConfig: { conversationId: '', body: '' },
  },
  'action.sendTeamChannelMessage': {
    icon: Hash,
    label: 'Message Channel',
    category: 'action',
    bg: 'bg-moss-500/10',
    text: 'text-moss-600',
    border: 'border-moss-400/40',
    description: 'Post a message to a team channel or DM.',
    defaultConfig: { channelId: '', body: '' },
  },
  'action.notifyEmployee': {
    icon: BellRing,
    label: 'Notify Employee',
    category: 'action',
    bg: 'bg-moss-500/10',
    text: 'text-moss-600',
    border: 'border-moss-400/40',
    description: 'Send a bell notification to an employee.',
    defaultConfig: { employeeId: '', title: '', body: '' },
  },
};

export const NODE_PALETTE: { category: NodeCategory; label: string; types: WorkflowNodeType[] }[] = [
  { category: 'trigger', label: 'Triggers', types: ['trigger.manual', 'trigger.cron', 'trigger.event'] },
  { category: 'logic', label: 'Logic', types: ['logic.if', 'logic.delay', 'logic.forEach', 'logic.setVariable', 'logic.merge'] },
  {
    category: 'action',
    label: 'Actions',
    types: [
      'action.createTask',
      'action.updateTask',
      'action.deleteTask',
      'action.createProject',
      'action.updateProject',
      'action.deleteProject',
      'action.createInvoice',
      'action.updateInvoiceStatus',
      'action.deleteInvoice',
      'action.sendClientMessage',
      'action.sendTeamChannelMessage',
      'action.notifyEmployee',
    ],
  },
];
